Autodesk Fusion 360/AutodeskFusion360.pkg.recipe, Dremel DigiLab 3D Slicer/DremelDigiLab3DSlicer.download.recipe, Dremel DigiLab 3D Slicer/DremelDigiLab3DSlicer.pkg.recipe, Express Scribe/ExpressScribe.download.recipe, Restor/Restor.download.recipe
Because variables can be overridden, it's a good idea to make sure that the recipe will still work even if a non-default variables used. One issue that would prevent recipes from running is using a `NAME` variable in paths that should be hard-coded (e.g. `/Applications/Foo.app`).
This PR removes the `NAME` variable from all file paths and replaces it with the actual app name, which should make the recipe more resilient for overrides.
=> Remove NAME variable from app paths

TestNav/SimpleJSONParser.py
In order to make your processors more compatible with AutoPkg running in Python 3, I've applied a few adjustments suggested by `python-modernize`, `pylint --py3k`, and `pylint` in general.
More adjustments may need to be made manually later, but this should catch the low-hanging fruit right now.
=> Basic python3 compatibility

TestNav/SimpleJSONParser.py
This PR adjusts the SimpleJSONParser processor to use the new [URLGetter superclass](https://github.com/autopkg/autopkg/wiki/Downloading-from-the-Internet-in-Custom-Processors), which will ease the transition to Python 3 and AutoPkg 2.
Here's a log of the adjusted processor in action, using the TestNav download recipe that references it:
https://gist.github.com/homebysix/294583c52e72ad3708ad06f1c948d626
=> Use URLGetter for SimpleJSONParser processor

Bitnami MAMP/BitnamiMAMP.pkg.recipe, Lightspeed Relay/RelaySmartAgent.pkg.recipe, Lightspeed Relay/RelaySmartAgentKextless.pkg.recipe, OpenWebStart/OpenWebStart.pkg.recipe, Prey/Prey.pkg.recipe, Scan Dimenson SOL/SOL.pkg.recipe
`pkgname` is [intended](https://github.com/autopkg/autopkg/blob/e36d5cba2823dbdfcb69a41a38b1aef9fb76121c/Code/autopkgserver/autopkgserver#L47) to be in the `pkg_request` dictionary, not as a standalone argument for [PkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-PkgCreator).
=> Adjust PkgCreator arguments

Google Drive/GoogleDrive.pkg.recipe
Extracts both the version and the minimum macOS version needed to run from the Google Drive app.  This would be useful to include in downstream .jss and .munki recipes
=> Replace Versioner with PlistReader in GoogleDrive.pkg.recipe

College Board/2021DigitalAPExams.download.recipe
Upside: there's now a YAML file showing the current file name, version number, and SHA256.
Downside: they put spaces in the URL that we have to encode.
=> CollegeBoard made their download page fancy

College Board/2021DigitalAPExams.download.recipe, College Board/DigitalAPExamURLProvider.py
Making proper use of that YAML feed that College Board provides, and properly URL-encoding the filename that they ever-so-helpfully put spaces in.
=> DigitalAPExamURLProvider

Cricut Design Space/CricutURLProvider.py, Cricut Design Space/SimpleJSONParser.py, Loom/LoomArchPicker.py, Pearson/SimpleJSONParser.py, TestNav/SimpleJSONParser.py
As of macOS Monterey 12.3, the version of Python 2 that shipped with macOS located at `/usr/bin/python` [has been removed](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes). More context can be found in some posts from Mac admins at the beginning of 2022, aggregated [here](https://scriptingosx.com/2022/03/macos-monterey-12-3-removes-python-2-link-collection/).
Since [version 2.0.2](https://github.com/autopkg/autopkg/releases/tag/v2.0.2), AutoPkg's installer has included its own Python 3 framework, symlinked from `/usr/local/autopkg/python`. This pull request adjusts the "shebang" interpreter paths of processors to replace `/usr/bin/python` with the AutoPkg Python 3 path.
NOTE: Because AutoPkg processors are imported as modules by AutoPkg and not …
=> Update Python path in processors to reflect changes in macOS 12.3+

1Password/1Password.download.recipe, 1Password/1Password.pkg.recipe
- added `%DOWNLOAD_BUILD%` input variable (choose between latest, latest.BETA, or latest.nightly)
- replaces `%DOWNLOAD_URL%` (but this input variable can still be set to avoid breaking existing recipe overrides)
=> added DOWNLOAD_BUILD input variable

1Password/1Password.munki.recipe, 1Password/1Password.pkg.recipe
https://macadmins.slack.com/archives/C056155B4/p1661459373289909
On every Munki recipe run 1Password being imported as new. `MunkiImporter` failed to find a matching item. After debugging found `%version%` and pkginfo's `version` didn't match. This uses `CFBundleVersion` which is the most complete version string available in Info.plist as of writing.
=> Fix 1Password duplicate imports

1Password/1Password.munki.recipe
- Remove blocking apps
- Kill `1Password` and `1Password 7` apps
- Make this an attended install
=> 1Password Munki recipe improvements

Wireshark/Wireshark.download.recipe, Wireshark/Wireshark.munki.recipe, Wireshark/Wireshark.pkg.recipe
Forked from https://github.com/autopkg/jleggat-recipes/tree/master/Wireshark I probably should have opened a PR there, but the changes were significant enough I figured the community could benefit from two different approaches. 
- Uses DMG for munkiimport
- Moves versioner to pkg recipe
- Supports multiple arch regex
=> Wireshark recipes

Okta Verify/OktaVerify.munki.recipe
This PR adds `exit 0` at the end of the Okta Verify uninstall script. Without this, the script will exit nonzero if no Okta receipt is found in the `pktuil --forget` command, which is undesirable.
=> Ensure Okta Verify uninstall succeeds even if no receipt is present

OBS/OBS.download.recipe, OBS/OBS.pkg.recipe
The new OBS files have different values for the architecture in the file name. It is now Intel or Apple
=> OBS change ARCH value to match new values

Okta Verify/OktaVerify.pkg.recipe
An alternate solution to https://github.com/autopkg/nstrauss-recipes/pull/60
=> Update OktaVerify.pkg.recipe to explicitly purge pkg payload directories

Okta Verify/OktaVerify.download.recipe
This should handle non-.com TLD's as well.
For example in our org we use a custom domain for Okta that this recipe wont be able to handle with .com hardcoded into the URL
This is the same pattern as used in the Okta terraform provider with an org_name and base_url variable: https://registry.terraform.io/providers/okta/okta/latest/docs#org_name
=> add ability for custom tld

VirusTotalReporter/VirusTotalReporter.py
AutoPkg pretty much assumes everything will always be a string. Otherwise it gets angry. Coerce summary results to string, which can be modified as needed later in whatever post-processing is done. Previously results were mixed string and integer anyway, which didn't make sense.
```python
The following items were queried from the VirusTotal database:
Traceback (most recent call last):
File "/usr/local/bin/autopkg", line 2786, in <module>
sys.exit(main(sys.argv))
File "/usr/local/bin/autopkg", line 2782, in main
return subcommands[verb]["function"](argv)
File "/usr/local/bin/autopkg", line 2391, in run_recipes
this_column = [len(row[column]) for row in rows]
File "/usr/local/bin/autopkg", line 2391, in <listcomp>
this_column = [len(row[column]) for row in rows]
TypeError: object of type …
```
=> VirusTotalReporter: Coerce summary results to string

VirusTotalReporter/README.md, VirusTotalReporter/VirusTotalReporter.py
- No longer count harmless detections as counting against the total score. VirusTotal doesn't. We shouldn't either.
- Attempt to use URL analysis in cases where the max file size exceeds 650 MB for new submissions.  See README changes for more details.
=> VirusTotalReporter: Implement URL analysis fallback support

VirusTotalReporter/VirusTotalReporter.py
When falling back to URL analysis, check for an existing report first like with files. Otherwise URLs were always been submitted for analysis. Faster to get a response and decreases the chance of getting rate limited.
=> VirusTotalReporter: Improve URL analysis report checking

Homebrew/Homebrew.download.recipe.yaml
The Apple Developer account signing the Homebrew installer switched with 4.3.9 from @MikeMcQuaid to @p-linnane as discussed https://macadmins.slack.com/archives/C10EVE8TS/p1720511467448949.
=> update homebrew installer signature

VirusTotalReporter/VirusTotalReporter.py
When supplying `submission_timeout` via the CLI (for example with `--key submission_timeout=450`), a type error is thrown because the CLI input is read as a string and then compared to an integer:
```
Error in local.download.FooBar: Processor: com.github.nstrauss.VirusTotalReporter/VirusTotalReporter: Error: '>' not supported between instances of 'int' and 'str'
```
This PR fixes that problem.
=> Ensure submission_timeout is an int

Mitel Connect/MitelConnect.download.recipe
Looks like Mitel re-signed with their own Dev ID instead of the old ShoreTel one.
=> Update MitelConnect code signature

NWEA Secure Testing Browser/NWEASecureTestingBrowser.download.recipe, NWEA Secure Testing Browser/NWEASecureTestingBrowser.pkg.recipe
- Resolves https://github.com/autopkg/nstrauss-recipes/issues/85
- Add code signature verification
- Move package recipe to `AppPkgCreator` to cut simplify steps
=> Update NWEA Secure Testing Browser download URL

Okta Verify/OktaVerify.munki.recipe
This removes the unpack and payload directories after use. I added this in my local override where I worked around the relocation issue and thought perhaps you'd want it as well. I will not feel bad if you prefer to keep them around and reject this PR.
=> Clean up unpack and payload directories after use.

VirusTotalReporter/VirusTotalReporter.py
My version of #89 Need to test before merging. Ensures there's a long enough timeout (5 minute default) set to wait for URL analysis from large files. Even though the URL is what's being analyzed, apparently large files still taking longer.
=> Create parity for URL fallback submission timeout

Autodesk Fusion/AutodeskFusion360.download.recipe, Autodesk Fusion/AutodeskFusion360.install.recipe, Autodesk Fusion/AutodeskFusion360.pkg.recipe
Fixes https://github.com/autopkg/nstrauss-recipes/issues/99
The recipe names and identifiers are staying as is for now to not introduce breaking changes. Will need to eventually rename them entirely.
=> Update recipes to account for Fusion 360 to Fusion transition

Vendini Box Office/VendiniBoxOffice.download.recipe, Vendini TicketAgent/VendiniTicketAgent.download.recipe
This PR deprecates Vendini Box Office and TicketAgent recipes, as the software is no longer publicly downloadable.
=> Deprecate Vendini Box Office and TicketAgent recipes

The Pack/ThePack.download.recipe
This PR deprecates The Pack recipes, as the software is now only available on the Mac App Store.
=> Deprecate ThePack recipes

1Password/1Password.download.recipe
As long as there is a valid `requirements` argument, the `expected_authority_names` argument is not needed for code signature verification. This pull request removes the unnecessary empty `expected_authority_names` array.
Thanks for considering!
This PR was submitted using [Repo Lasso](https://github.com/homebysix/repo-lasso) v1.2.0.
=> Remove empty `expected_authority_names` array in CodeSignatureVerifier arguments

Anki/Anki.download.recipe, Anki/Anki.pkg.recipe
This PR switches the parent recipe of Anki.pkg to the hansen-m download recipe, and deprecates the download recipe in this repo.
Verbose recipe run output:
```
% autopkg run -vvq Anki.pkg.recipe
Processing Anki.pkg.recipe...
WARNING: Anki.pkg.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
{'Input': {'asset_regex': '.*apple.*', 'github_repo': 'ankitects/anki'}}
GitHubReleasesInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
GitHubReleasesInfoProvider: No value supplied for GITHUB_URL, setting default value of: https://api.github.com
GitHubReleasesInfoProvider: No value supplied for GITHUB_TOKEN_PATH, setting default value of: ~/.autopkg_gh_token
GitHubReleasesInfoProvider: Matched …
```
=> Change parent recipe of Anki.pkg

Homebrew/Homebrew.munki.recipe.yaml
https://github.com/autopkg/nstrauss-recipes/issues/92
- Checks to see if a user account is logged in. [The brew .pkg's preinstall script will fail if no user account is logged in](https://github.com/Homebrew/brew/blob/4ee6e96bdf857b3c50290bf032a9645b3bf293f1/package/scripts/preinstall#L13), which would result in an install loop at the login window.
- Adds debug output for the /Library/Managed Installs/Logs/ManagedSoftwareupdate.log
- Runs the `brew --version` command as the logged in user, as it fails to run properly as root
- Compressed if/then/else to if/else for version comparison
- Leverages [is-at-least](https://scriptingosx.com/2019/11/comparing-version-strings-in-zsh/) so that Munki won't _downgrade_ `brew` if users update `brew` before the next AutoPkg run
=> Fix for install loop for Homebrew Munki recipe

Homebrew/Homebrew.munki.recipe.yaml
To avoid an install loop. More details in https://github.com/autopkg/nstrauss-recipes/issues/102
=> For cleaner upgrade, have Homebrew .munki recipe delete old Homebrew subdirs first

kubectl/kubectl.download.recipe
- Update kubectl download URLs according to docs https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/#install-kubectl-binary-with-curl-on-macos
- Make the default arch arm64. Good bye, Intel.
=> Update kubectl download URL
